# fly.toml app configuration file generated for helio-bot on 2023-09-03T16:13:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "helio-bot"
primary_region = "scl"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
