name = "bot-muramasa"   # Debe coincidir EXACTAMENTE con el nombre en el dashboard
main = "src/index.js"           # O donde esté tu entry point
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]
[observability.logs]
enabled = false
invocation_logs = true
